#!/usr/bin/env python3
"""
generate_standards.py — Consolidate bcquality layers into al_standards.md.

Reads all .md rule files from microsoft/, community/, and custom/ folders,
strips the YAML frontmatter (preserving bc-version annotations), and writes
a single al_standards.md document. Then uploads it to the quinn-assets blob
container.

Usage:
    python scripts/generate_standards.py [--output al_standards.md] [--upload]

Environment (required when --upload is set):
    AZURE_STORAGE_CONNECTION_STRING or AZURE_STORAGE_ACCOUNT_NAME (Managed Identity)
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


_FRONTMATTER_RE = re.compile(r"^---\s*\n.*?^---\s*\n", re.DOTALL | re.MULTILINE)
_BC_VERSION_RE = re.compile(r"^bc-version:\s*\n((?:[ \t]*- [^\n]+\n)+)", re.MULTILINE)

_LAYER_ORDER = [
    ("microsoft", "Microsoft Quality Standards (Layer 1)"),
    ("community", "Community Standards (Layer 2)"),
    ("custom", "NAV-X Organisation Standards (Layer 3)"),
]

_REPO_ROOT = Path(__file__).parent.parent


def _extract_bc_versions(frontmatter: str) -> list[str]:
    m = _BC_VERSION_RE.search(frontmatter)
    if not m:
        return []
    return [line.strip().lstrip("- ") for line in m.group(1).splitlines() if line.strip()]


def _strip_frontmatter(text: str) -> str:
    return _FRONTMATTER_RE.sub("", text, count=1).lstrip("\n")


def _collect_layer(folder: Path) -> list[tuple[str, list[str], str]]:
    """Return (filename_stem, bc_versions, stripped_content) for every .md file in folder."""
    entries: list[tuple[str, list[str], str]] = []
    if not folder.is_dir():
        return entries
    for path in sorted(folder.rglob("*.md")):
        if path.name.upper() == "README.MD":
            continue
        raw = path.read_text(encoding="utf-8")
        fm_match = _FRONTMATTER_RE.match(raw)
        bc_versions = _extract_bc_versions(fm_match.group(0)) if fm_match else []
        content = _strip_frontmatter(raw).strip()
        if content:
            entries.append((path.stem, bc_versions, content))
    return entries


def generate(output_path: Path) -> str:
    sections: list[str] = [
        "# NAV-X AL Coding Standards\n\n"
        "> Auto-generated from nav-x-llc/bcquality. "
        "Edit source files in the fork — do not edit this file directly.\n"
    ]

    total_rules = 0
    for folder_name, title in _LAYER_ORDER:
        folder = _REPO_ROOT / folder_name
        entries = _collect_layer(folder)
        if not entries:
            continue
        sections.append(f"\n---\n\n## {title}\n")
        for _stem, bc_versions, content in entries:
            version_note = ""
            if bc_versions:
                version_note = f"\n> **Applies to:** BC {' · '.join(bc_versions)}\n"
            sections.append(f"\n{version_note}{content}\n")
        total_rules += len(entries)

    doc = "\n".join(sections)
    output_path.write_text(doc, encoding="utf-8")
    print(f"Generated {output_path} ({len(doc)} chars, {total_rules} rules)")  # noqa: T201
    return doc


def upload(content: str) -> None:
    """Upload al_standards.md to the quinn-assets blob container."""
    conn_str = os.environ.get("QUINN_STORAGE") or os.environ.get("AZURE_STORAGE_CONNECTION_STRING")
    account_name = os.environ.get("AZURE_STORAGE_ACCOUNT_NAME")

    if conn_str:
        from azure.storage.blob import BlobServiceClient
        client = BlobServiceClient.from_connection_string(conn_str)
    elif account_name:
        from azure.identity import DefaultAzureCredential
        from azure.storage.blob import BlobServiceClient
        client = BlobServiceClient(
            account_url=f"https://{account_name}.blob.core.windows.net",
            credential=DefaultAzureCredential(),
        )
    else:
        print("ERROR: set QUINN_STORAGE, AZURE_STORAGE_CONNECTION_STRING, or AZURE_STORAGE_ACCOUNT_NAME")  # noqa: T201
        sys.exit(1)

    blob = client.get_blob_client(container="quinn-assets", blob="al_standards.md")
    blob.upload_blob(content.encode("utf-8"), overwrite=True)
    print("Uploaded al_standards.md to quinn-assets blob container")  # noqa: T201


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="al_standards.md")
    parser.add_argument("--upload", action="store_true")
    args = parser.parse_args()

    output_path = Path(args.output)
    doc = generate(output_path)
    if args.upload:
        upload(doc)


if __name__ == "__main__":
    main()
